#!/usr/bin/env bash
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"; CHILD_PIDS=()
load_env_file(){ local key value; while IFS='=' read -r key value; do key="${key#export }"; [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue; [ -z "${!key+x}" ] || continue; value="${value%$'\r'}"; if [[ "$value" == \"*\" && "$value" == *\" ]]; then value="${value:1:${#value}-2}"; elif [[ "$value" == \'*\' && "$value" == *\' ]]; then value="${value:1:${#value}-2}"; fi; export "$key=$value"; done < "$PROJECT_DIR/.env"; }
require_file(){ [ -f "$1" ] || { echo "Missing required file: $1" >&2; exit 1; }; }; require_dir(){ [ -d "$1" ] || { echo "Missing dependencies: $1 (install explicitly before startup)" >&2; exit 1; }; }
port_free(){ if command -v lsof >/dev/null 2>&1 && lsof -tiTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1; then echo "Port $1 is already in use; refusing to terminate another process." >&2; exit 1; fi; }; cleanup(){ for pid in "${CHILD_PIDS[@]:-}"; do [ -n "$pid" ] && kill "$pid" 2>/dev/null || true; done; }; trap cleanup INT TERM EXIT
require_file "$PROJECT_DIR/.env"; load_env_file; BACKEND_PORT="${BACKEND_PORT:-${PORT:?PORT or BACKEND_PORT is required}}"; FRONTEND_PORT="${FRONTEND_PORT:?FRONTEND_PORT is required}"; export CORS_ORIGINS="${CORS_ORIGINS:-http://${FRONTEND_HOST:-127.0.0.1}:$FRONTEND_PORT}"; require_dir "$PROJECT_DIR/backend/node_modules"; require_dir "$PROJECT_DIR/frontend/node_modules"; port_free "$BACKEND_PORT"; port_free "$FRONTEND_PORT"
(cd "$PROJECT_DIR/backend" && BACKEND_PORT="$BACKEND_PORT" npm start) & CHILD_PIDS+=("$!"); (cd "$PROJECT_DIR/frontend" && VITE_BACKEND_PORT="$BACKEND_PORT" VITE_FRONT_PORT="$FRONTEND_PORT" npm run dev -- --host "${FRONTEND_HOST:-127.0.0.1}" --port "$FRONTEND_PORT") & CHILD_PIDS+=("$!")
echo "Governed image services started without installing, seeding, migrating, or reclaiming ports."; wait "${CHILD_PIDS[@]}"
